In [35]:
import dask.dataframe as ddf
import pandas as pd
from datetime import datetime
import numpy as np

In [37]:
PATH = "timeseries.csv"

# We have write the datatypes for the appropriate columns as this should be most important step in the Dask as it will not be confused

In [40]:
data_types = {"name" : "str",
                "level" : "str",
                "city" : "str",
                "county" : "str",
                "state" : "str",
                "country" : "str",
                "population" : "float",
                "lat" : "float",
                "long" : "float",
                "url" : "str",
                "aggregate" : "str",
                "tz" : "str",
                "cases" : "float",
                "deaths" : "float",
                "recovered" : "str",
                "active" : "str",
                "tested" : "str",
                "hospitalized" : "str",
                "hospitalized_current" : "str",
                "discharged" : "str",
                "icu" : "str",
                "icu_current" : "str",
                "growthFactor" : "str",
                "date" : "str"}

# reading the data as dask dataframe

In [43]:
df = ddf.read_csv(PATH, dtype = data_types)

# see the all countries as they we can figure out what exactly the US string such taht we can filter that

In [46]:
df.groupby(by = ["country"]).count().compute().reset_index()["country"].tolist()

['Afghanistan',
 'Albania',
 'Algeria',
 'Andorra',
 'Angola',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bhutan',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Brunei',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cape Verde',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo-Brazzaville',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czechia',
 "Côte d'Ivoire",
 'Democratic Republic of the Congo',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'East Timor',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Eswatini',
 'Ethiopia',
 'Fiji',
 'Finland',
 'France',
 'Gabon',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Greenland',
 'Grenada',
 'Guam',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kosovo',
 'Kuwait',
 'Kyrgyzstan',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Moldova',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nepal',
 'Netherlands',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North Macedonia',
 'Northern Mariana Islands',
 'Norway',
 'Oman',
 'Pakistan',
 'Palestinian Territories',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Qatar',
 'Romania',
 'Russia',
 'Rwanda',
 'Sahrawi Arab Democratic Republic',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Vincent and the Grenadines',
 'San Marino',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'Somalia',
 'South Africa',
 'South Korea',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Sweden',
 'Switzerland',
 'Syria',
 'São Tomé and Príncipe',
 'Taiwan',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'The Bahamas',
 'The Gambia',
 'Togo',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United States',
 'United States Virgin Islands',
 'Uruguay',
 'Uzbekistan',
 'Vatican City',
 'Venezuela',
 'Vietnam',
 'Yemen',
 'Zambia',
 'Zimbabwe']

# format the date column as we can perfrom date aggregation operations

In [48]:
df["date"] = ddf.to_datetime(df["date"], format="%Y-%m-%d")

In [49]:
# from above we canunderstand that from the dataset we have two sections that contains united states lets initally filter them
# here we are using the distributed computing as dask tuned for that
df_us = df[df["country"] == "United States"] #, "United States Virgin Islands"])]

In [50]:
df_us.head()

,name,level,city,county,state,country,population,lat,long,url,...,recovered,active,tested,hospitalized,hospitalized_current,discharged,icu,icu_current,growthFactor,date
24958,"Washoe County, Nevada, United States",county,NaN,Washoe County,Nevada,United States,471519.0,40.582,-119.5885,https://services.arcgis.com/iCGWaR7ZHc5saRIl/a...,...,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-05
24959,"Washoe County, Nevada, United States",county,NaN,Washoe County,Nevada,United States,471519.0,40.582,-119.5885,https://services.arcgis.com/iCGWaR7ZHc5saRIl/a...,...,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,1,2020-03-06
24960,"Washoe County, Nevada, United States",county,NaN,Washoe County,Nevada,United States,471519.0,40.582,-119.5885,https://services.arcgis.com/iCGWaR7ZHc5saRIl/a...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2020-03-07
24961,"Washoe County, Nevada, United States",county,NaN,Washoe County,Nevada,United States,471519.0,40.582,-119.5885,https://services.arcgis.com/iCGWaR7ZHc5saRIl/a...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2020-03-08
24962,"Washoe County, Nevada, United States",county,NaN,Washoe County,Nevada,United States,471519.0,40.582,-119.5885,https://services.arcgis.com/iCGWaR7ZHc5saRIl/a...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2020-03-09

In [51]:
df.shape[0].compute()

397882

In [52]:
start_date = datetime.strptime("2020-01-01", r"%Y-%m-%d")
end_date = datetime.strptime("2021-02-28", r"%Y-%m-%d")


# here we are using the distributed computing as dask tuned for that
# now lets perfrom the filtering using the dates defined above
df_us_dt = df_us[(df_us["date"]>=start_date) & (df_us["date"]<=end_date)]

In [53]:
# see the shape as this can be useful for me to check whether we did really filter the data
df_us_dt.shape[0].compute()

310313

In [54]:
df_us_dt.head()

,name,level,city,county,state,country,population,lat,long,url,...,recovered,active,tested,hospitalized,hospitalized_current,discharged,icu,icu_current,growthFactor,date
24958,"Washoe County, Nevada, United States",county,NaN,Washoe County,Nevada,United States,471519.0,40.582,-119.5885,https://services.arcgis.com/iCGWaR7ZHc5saRIl/a...,...,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-05
24959,"Washoe County, Nevada, United States",county,NaN,Washoe County,Nevada,United States,471519.0,40.582,-119.5885,https://services.arcgis.com/iCGWaR7ZHc5saRIl/a...,...,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,1,2020-03-06
24960,"Washoe County, Nevada, United States",county,NaN,Washoe County,Nevada,United States,471519.0,40.582,-119.5885,https://services.arcgis.com/iCGWaR7ZHc5saRIl/a...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2020-03-07
24961,"Washoe County, Nevada, United States",county,NaN,Washoe County,Nevada,United States,471519.0,40.582,-119.5885,https://services.arcgis.com/iCGWaR7ZHc5saRIl/a...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2020-03-08
24962,"Washoe County, Nevada, United States",county,NaN,Washoe County,Nevada,United States,471519.0,40.582,-119.5885,https://services.arcgis.com/iCGWaR7ZHc5saRIl/a...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2020-03-09

In [55]:
# Compute total deaths for each state during the period
total_deaths = df_us_dt.groupby('state')['deaths'].sum().compute()

# Compute the average population for each state during the period
# You might want to average the population over the period for each state
avg_population = df_us_dt.groupby('state')['population'].mean().compute()

# Now, calculate the per-capita mortality as deaths / population
per_capita_mortality = total_deaths / avg_population

# Rank states based on per-capita mortality
ranked_states = per_capita_mortality.sort_values(ascending=False)

# Show the ranked states
print(ranked_states)

state
New York                        6.395701
Michigan                        3.204753
Louisiana                       2.735288
Illinois                        2.043863
New Jersey                      2.031200
Georgia                         2.026085
Pennsylvania                    1.831572
Virginia                        1.359063
Mississippi                     1.356705
Indiana                         1.353423
Ohio                            1.058943
Iowa                            0.958771
Massachusetts                   0.904775
Colorado                        0.894296
Minnesota                       0.768853
Kentucky                        0.751512
Texas                           0.737643
Missouri                        0.711146
Connecticut                     0.677952
Maryland                        0.658347
Alabama                         0.599759
North Carolina                  0.549190
Florida                         0.545793
Wisconsin                       0.437617
Nebraska                        0.397699
Oklahoma                        0.397603
Tennessee                       0.375231
California                      0.371347
Washington                      0.359377
Kansas                          0.330341
New Mexico                      0.327128
South Carolina                  0.315557
Arkansas                        0.271762
Rhode Island                    0.220419
South Dakota                    0.215476
North Dakota                    0.204487
West Virginia                   0.136558
Nevada                          0.126360
New Hampshire                   0.123780
Idaho                           0.118306
Vermont                         0.101814
Oregon                          0.098453
Delaware                        0.095738
Maine                           0.077630
Washington, D.C.                0.045661
Utah                            0.044994
Wyoming                         0.028398
Arizona                         0.028349
Montana                         0.025902
Alaska                          0.019541
United States Virgin Islands    0.002364
Northern Mariana Islands        0.001922
Hawaii                          0.001786
Puerto Rico                     0.001670
Guam                            0.001585
American Samoa                  0.000000
NaN                                  NaN
dtype: float64

In [56]:
def year_month_udf(col):
    return f"{col.year}_{col.month}"

In [57]:
# Q3.3 for this extract the string year-month
# here we are using the distributed computing as dask tuned for that
df_us_dt["year_month"] = df_us_dt["date"].apply(year_month_udf)

total_cases = df_us_dt.groupby(by = ["state", "year_month"])["cases"].sum().compute()

total_deaths = df_us_dt.groupby(by = ["state", "year_month"])["deaths"].sum().compute()

CFR = (total_deaths / total_cases) * 100

CFR = CFR.reset_index()

pivot_table = CFR.pivot(index='state', columns='year_month')

/opt/anaconda3/lib/python3.12/site-packages/dask_expr/_collection.py:4376: UserWarning:
You did not provide metadata, so Dask is running your function on a small dataset to guess output types. It is possible that Dask will guess incorrectly.
To provide an explicit output types or to silence this message, please provide the `meta=` keyword, as described in the map or apply function that you are using.
  Before: .apply(func)
  After:  .apply(func, meta=('date', 'object'))

  warnings.warn(meta_warning(meta))

In [58]:
df_us_dt["year_month"].unique().compute().tolist()

['2020_3', '2020_4', '2020_5', '2020_6', '2020_7', '2020_1', '2020_2']

In [59]:
# pivot_table.reset_index(inplace = True)
pivot_table.columns = ['2020_1', '2020_2', '2020_3', '2020_4', '2020_5', '2020_6', '2020_7']

# we are verifying the dataset we can clearly see that there is not data related to the 2021 year at all

In [61]:
# fill the missing records
pivot_table["2020_8"] = np.nan
pivot_table["2020_9"] = np.nan
pivot_table["2020_10"] = np.nan
pivot_table["2020_11"] = np.nan
pivot_table["2020_12"] = np.nan
pivot_table["2021_1"] = np.nan
pivot_table["2021_2"] = np.nan

pivot_table = pivot_table[['2020_1', '2020_2', '2020_3', '2020_4', '2020_5', '2020_6', '2020_7',
                           '2020_8', '2020_9', '2020_10', '2020_11', '2020_12', '2021_1', '2021_2']]

In [62]:
pivot_table

,2020_1,2020_2,2020_3,2020_4,2020_5,2020_6,2020_7,2020_8,2020_9,2020_10,2020_11,2020_12,2021_1,2021_2
state,,,,,,,,,,,,,,
Alabama,NaN,NaN,0.532313,2.830899,3.889270,2.962907,2.381771,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Alaska,NaN,NaN,0.335008,2.314519,2.196905,1.303247,1.207417,NaN,NaN,NaN,NaN,NaN,NaN,NaN
American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Arizona,0.0,0.000000,0.000000,1.486545,1.992175,0.211513,0.973523,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Arkansas,NaN,NaN,0.915656,1.911450,2.129628,1.515155,1.274360,NaN,NaN,NaN,NaN,NaN,NaN,NaN
California,0.0,0.000000,2.006735,3.479974,3.983350,3.178666,2.543001,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Colorado,NaN,NaN,0.939250,2.636616,5.372019,5.419220,5.063691,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Connecticut,NaN,NaN,1.814771,6.477626,9.016204,9.383106,9.500807,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Delaware,NaN,NaN,1.334107,2.734038,3.574849,4.164733,4.013148,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Florida,NaN,NaN,0.842669,2.905738,4.277250,3.404313,2.039752,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Georgia,NaN,NaN,2.185574,3.980977,4.452969,4.312292,3.263239,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Guam,NaN,NaN,2.702703,3.615483,3.186275,2.750275,1.774308,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Hawaii,NaN,NaN,0.036271,0.000000,0.481140,1.923594,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Idaho,NaN,NaN,1.448967,2.258980,3.026976,2.255316,1.385931,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Illinois,0.0,0.000000,1.288155,4.048394,4.427381,4.760111,4.802791,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Indiana,NaN,NaN,2.396460,4.775795,5.564376,5.849879,5.314359,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Iowa,NaN,NaN,0.863465,2.326472,2.433142,2.682311,2.364454,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Kansas,NaN,NaN,0.989866,2.364135,1.423958,1.998686,1.781868,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Kentucky,NaN,NaN,2.225112,5.074331,4.666360,4.045568,3.706810,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Louisiana,NaN,NaN,3.916843,5.191232,7.010445,6.157174,5.138853,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Maine,NaN,NaN,0.529355,3.778067,4.182856,3.583397,3.156923,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Maryland,NaN,NaN,0.261008,3.684368,4.806133,4.670979,4.649307,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Massachusetts,NaN,0.000000,0.499505,4.415282,6.625696,7.247411,7.437951,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Michigan,NaN,NaN,2.493512,7.508176,9.902791,9.097596,8.623360,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Minnesota,NaN,NaN,0.000000,2.527566,3.052268,4.173187,3.958075,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Mississippi,NaN,NaN,1.504930,3.296058,4.593225,4.455260,3.743453,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Missouri,NaN,NaN,1.196568,2.878952,4.774436,5.578889,3.979086,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Montana,NaN,NaN,0.000000,0.966368,2.283996,2.792962,1.555189,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Nebraska,NaN,0.000000,0.000000,1.422412,1.257609,1.359915,1.443365,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Nevada,NaN,NaN,2.033319,4.051924,4.970358,3.830004,2.541570,NaN,NaN,NaN,NaN,NaN,NaN,NaN
New Hampshire,NaN,NaN,0.268757,1.546978,4.025026,5.992573,6.436738,NaN,NaN,NaN,NaN,NaN,NaN,NaN
New Jersey,NaN,NaN,0.401749,4.064989,6.934022,7.773725,8.251406,NaN,NaN,NaN,NaN,NaN,NaN,NaN
New Mexico,NaN,NaN,0.705290,2.949834,4.336271,4.409418,4.003795,NaN,NaN,NaN,NaN,NaN,NaN,NaN
New York,NaN,NaN,2.075213,6.525716,7.365287,7.321241,7.233961,NaN,NaN,NaN,NaN,NaN,NaN,NaN
North Carolina,NaN,NaN,0.331498,2.722044,3.471947,2.512702,1.987512,NaN,NaN,NaN,NaN,NaN,NaN,NaN
North Dakota,NaN,NaN,0.253646,0.893946,1.346565,2.194075,2.215880,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Northern Mariana Islands,NaN,NaN,NaN,14.468085,10.569106,7.042254,6.535948,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ohio,NaN,NaN,1.529431,4.404734,5.865587,6.024960,5.275945,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Oklahoma,NaN,NaN,2.833876,5.439956,5.568855,3.909534,2.656809,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Oregon,NaN,0.000000,2.660322,3.617323,3.837110,2.944807,2.237008,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Pennsylvania,NaN,NaN,1.081428,3.292275,6.835164,7.506220,7.418973,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Puerto Rico,NaN,NaN,NaN,5.808946,4.524982,2.773468,1.998391,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Rhode Island,NaN,NaN,0.061703,1.516496,3.314532,5.476087,5.821287,NaN,NaN,NaN,NaN,NaN,NaN,NaN
South Carolina,NaN,NaN,1.964286,2.882223,4.344983,2.894657,1.922291,NaN,NaN,NaN,NaN,NaN,NaN,NaN
South Dakota,NaN,NaN,0.775194,0.453175,1.074754,1.282311,1.383357,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Tennessee,NaN,NaN,0.036523,1.964376,1.655256,1.513466,1.302543,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Texas,NaN,0.000000,1.184979,2.403974,2.737519,2.009166,1.392601,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States Virgin Islands,NaN,NaN,NaN,5.223881,7.835400,8.379888,5.976096,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Utah,NaN,0.000000,0.179292,0.446306,0.630986,0.808203,0.362686,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Vermont,NaN,NaN,3.411633,4.238581,5.710436,4.977477,4.559147,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Virginia,NaN,NaN,1.406402,2.865308,3.315829,2.862225,2.841844,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Washington,0.0,1.360544,5.051079,5.255217,5.308562,4.396312,3.921734,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Washington, D.C.",NaN,NaN,1.436880,3.736434,5.264651,5.289760,5.330110,NaN,NaN,NaN,NaN,NaN,NaN,NaN
West Virginia,NaN,NaN,0.000000,2.181204,3.136926,3.638010,3.004665,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Wisconsin,NaN,0.000000,0.852336,4.482942,3.625332,2.998631,2.495788,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Wyoming,NaN,NaN,0.000000,0.396069,0.779409,1.514208,0.634035,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Q3.4 Using this matrix as input, compute the ranking of states, on how the CFR rate changed over time. This computation will involve an aggregation of of month-to-month changes in CFR. Note that some of these month-to-month changes can be positive (CFR increases from a previous month to the current month) or negative (CFR decrease from a previous month to the current month), or zero (no change in CFR). You need to aggregate these individual changes, across all time periods.

In [92]:
# here we are using normal computation as the data is smaller dataframe
pivot_table["total_cfr"] = pivot_table.abs().sum(axis = 1)

In [65]:
pivot_table['rank'] = pivot_table['total_cfr'].rank(ascending=False, method='min')

In [66]:
pivot_table = pivot_table.sort_values(by='rank')

In [90]:
pivot_table[["total_cfr", "rank"]]

                              total_cfr  rank
state
Northern Mariana Islands      38.615392   1.0
Michigan                      37.625435   2.0
Connecticut                   36.192514   3.0
New York                      30.521418   4.0
New Jersey                    27.425891   5.0
United States Virgin Islands  27.415265   6.0
Louisiana                     27.414547   7.0
Massachusetts                 26.225845   8.0
Pennsylvania                  26.134059   9.0
Washington                    25.293449  10.0
Indiana                       23.900870  11.0
Ohio                          23.100657  12.0
Vermont                       22.897274  13.0
Washington, D.C.              21.057835  14.0
Oklahoma                      20.409031  15.0
Kentucky                      19.718182  16.0
Colorado                      19.430796  17.0
Illinois                      19.326830  18.0
Missouri                      18.407930  19.0
New Hampshire                 18.270072  20.0
Georgia                       18.195052  21.0
Maryland                      18.071796  22.0
Mississippi                   17.592925  23.0
Nevada                        17.427175  24.0
New Mexico                    16.404608  25.0
Rhode Island                  16.190105  26.0
Delaware                      15.820874  27.0
Oregon                        15.296570  28.0
Maine                         15.230598  29.0
California                    15.191726  30.0
Puerto Rico                   15.105786  31.0
Wisconsin                     14.455027  32.0
Guam                          14.029043  33.0
South Carolina                14.008439  34.0
Minnesota                     13.711096  35.0
Florida                       13.469722  36.0
Virginia                      13.291607  37.0
Alabama                       12.597160  38.0
West Virginia                 11.960805  39.0
North Carolina                11.025704  40.0
Iowa                          10.669844  41.0
Idaho                         10.376169  42.0
Texas                          9.728239  43.0
Kansas                         8.558513  44.0
Arkansas                       7.746251  45.0
Montana                        7.598515  46.0
Alaska                         7.357096  47.0
North Dakota                   6.904112  48.0
Tennessee                      6.472164  49.0
Nebraska                       5.483301  50.0
South Dakota                   4.968789  51.0
Arizona                        4.663757  52.0
Wyoming                        3.323721  53.0
Hawaii                         2.441006  54.0
Utah                           2.427472  55.0
American Samoa                 0.000000  56.0